### ISSUE TITLE
Water Sampling Tables

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#12] opened 2015-06-26 17:48 UTC
We figured these would be a problem. And they are. Pretty much incomprehensible at phone size because they have so many fields. Any thoughts on how to solve this?

New:
http://staging.baltimorecountymd.gov/homepageredesign/Agencies/health/environmentalhealth/watersampling/samplingresults/gunpowder.html

Old:
http://www.baltimorecountymd.gov/Agencies/health/environmentalhealth/watersampling/samplingresults/gunpowder.html

**Comment by martypowell** [comment] 2015-06-29 12:40
[Here](http://codepen.io/martypowell/pen/yNpEOO?editors=001) is a JavaScript solution to the problem.  We would need to include this script on each page that contains a table and apply the script and a certain screen size (TBD).  

Right labels and data are structured like, ``<p>label-value</p>``.  This can easily be changed, just wanted to get something up quick.

**Comment by mxsnyder** [comment] 2017-01-10 21:44
@danfox01 is this still an issue?

**Comment by danfox01** [comment] 2017-01-10 22:02
@mxsnyder I don't think so. I actually forgot about this particular issue, but it is closely related to the email I sent you last week about large table formatting in general.

Something to look into...

**Comment by mxsnyder** [comment] 2017-01-11 14:05
So this is actually a feature request and not a bug? :) I'll add a "nifty tables" feature to VSTS, with stories for making them responsive and sortable by column.

**Comment by mxsnyder** [comment] 2017-01-11 14:08
Added the [feature](https://baltimore-county-mxsnyder.visualstudio.com/baltimorecountymd-gov/_workitems?id=125&_a=edit) to VSTS. Closing out.

**Closed by mxsnyder** 2017-01-11 14:08 UTC
Labels: bug
