### ISSUE TITLE
BaltcoGo - Add ability to disable form on certain sub categories

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#235] opened 2018-08-13 18:52 UTC
I talked to Eric today and he suggested we want to disable  or hide next prev buttons when a certain subcategory is selected. We should use this opportunity to finish this issue as well #169 . More details to follow.

**Comment by etenney** [comment] 2018-08-13 19:52
Please let me know if you need anything else.

**Comment by danfox01** [comment] 2018-12-27 19:39
Bingo. @martypowell and @tmccoy529, closing this. Duplicate of #249

**Closed by danfox01** 2018-12-27 19:39 UTC
Labels: BaltCoGo, duplicate
