### ISSUE TITLE
Survey Monkey Survey Displaying multiple times when it shouldn't

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/baltimorecountymd.gov-assets#240] opened 2018-09-05 18:18 UTC
The HTML snippet for the survey monkey form is located on the Red Inside template. Some users are reporting that the survey is popping up multiple times during a session, which should not be the case.

**Comment by jdomasky** [comment] 2018-09-05 18:33
@sdurphy @martypowell I can confirm this is true. Julie and I have discussed this problem. It happens for me in different browsers on different PCs/devices. Sometimes it's so repetitious that I don't dismiss it and I end up browsing a page with the invitation in place.

**Comment by danfox01** [comment] 2018-09-05 18:54
@sdurphy let's remove this since it's not working as expected. We should have tested it more thoroughly before releasing it. We can re-release when it's figured out.

**Comment by sdurphy** [comment] 2018-09-05 19:01
removed. thanks everyone

**Comment by martypowell** [comment] 2018-09-06 12:09
@sdurphy can we restore this in dev, so that we can test?

**Comment by danfox01** [comment] 2018-09-27 18:11
Couldn't resolve this but we suspect it's an SE template issue. Closing, since the survey is now closed and the issue is moot.

**Closed by danfox01** 2018-09-27 18:11 UTC
Labels: BCG, Bug, wontfix
